oidc:
  clientId: "test"
  clientSecret: ""
  issuer: "https://YOUR_DOMAIN/auth/realms/hyperplane/.well-known/openid-configuration"
  scopes:
    - openid
    - profile
    - email
  insecureSkipVerify: true
